[bazel]
agility_software_repo = "~/code/agility-software"

[[port-forward.groups]]
name = "group1"  
services = [  
  { name = "workflow-management", namespace = "development", local_port = 8081 },  
  { name = "message-handler", namespace = "development", local_port = 8082 },  
  { name = "workcell-monolith", namespace = "development", local_port = 8083 },  
]  
